import symbols from "./symbols";

export default {
  MainMenuLabel: symbols.MagicEmo + " Главное меню " + symbols.MagicEmo,
  SettingsMenuLabel: symbols.GearEmo + " Настройки",
  AdvancedMenuLabel: symbols.MagicBallEmo + " Дополнительно",
  P2PCalcLabel: symbols.P2PEmo + " Рассчитать P2P-пару",
  CIDRCalcLabel: symbols.NetworkEmo + " Расчет сети",
  DOFLabel: symbols.ShieldEmo + " Дежурный сотрудник",
  DSLabel: symbols.Group1 + " График дежурств",
  RequestLabel: symbols.MoyaiEmo + " Запрос на обслуживание",
  SubnetCalcLabel: symbols.PcEmo + " Калькулятор подсети",
  MIAllertLabel: symbols.MagicEmo + " Массовый инцидент",
  MassMailingLabel: symbols.RuporEmo + " Массовая рассылка",
  PingDeviceLabel: symbols.CLI + " Ping",
  EnterLabel: symbols.GreenCircleEmo + " Войти",
  ExitLabel: symbols.RedCircleEmo + " Выйти",
  BackLabel: symbols.BackEmo + " Назад",
  CancelLabel: symbols.CancelEmo + " Отмена",
  Continue: symbols.OkEmo + " Продолжить",

  AdminLabel: symbols.TechnologyEmo + " Администрирование системы",
  AppLogLabel: symbols.LOG + " Логи системы",
 ApiTokenCreate: symbols.LockManagerEmo + " Создать API-token",
  UserAdminLabel: symbols.UserEmo + " Пользователи системы",
  NoAcepptUsersLabel: symbols.AlienEmo + " Не активированные",
  AcepptUsersLabel: symbols.MoyaiEmo + " Активированные",
  AdminsUsersLabel: symbols.SantaEmo + " Администраторы",
  SendContactLabel: symbols.ShareEmo + " Поделиться контактом",
  CheckDeviceLabel: symbols.MagnifierEmo + " Проверить устройство",
  DDMInfoLabel: symbols.DDMEmo + " DDM информация",
  VlanListLabel: symbols.VlanEmo + " Список VLAN",
  PortInfoLabel: symbols.TestTubeEmo + " Состояние портов",
  CabelLengthLabel: symbols.LinerEMO + " Замер длинны кабеля",
  DeviceLLDPLabel: symbols.CROSSTALK + " LLDP Информация",
  TrafficGraphLabel: symbols.Group1 + " Трафик на устройстве",
  MMPriorityHigh: symbols.RedCircleEmo + " Высокий!",
  MMPriorityAverage: symbols.YellovCircleEmo + " Средний!",
  MMPriorityShort: symbols.GreenCircleEmo + " Низкий!",
  MMPriorityInfo: symbols.BlueCircleEmo + " Информация!",
  MMPriorityZeroDay: symbols.BlackCircleEmo + " Нулевого дня!",
  H06TrafficGraphLabel: symbols.Group1 + " 6 Hours",
  H24TrafficGraphLabel: symbols.Group1 + " 1 Day",
  H48TrafficGraphLabel: symbols.Group1 + " 2 Days",
  W01Traffic1wGraphLabel: symbols.Group1 + " One Week",
  M01TrafficGraphLabel: symbols.Group1 + " One Month",
  M03TrafficGraphLabel: symbols.Group1 + " Three Months",
  Y01TrafficGraphLabel: symbols.Group1 + " One Year",
  UserAllowLabel:symbols.OK_UP +" Добавить пользователя"
};
