export default {
  UpEmo: "✅",
  DownEmo: "❌",
  WarnEmo: "⚠️",
  CritEmo: "❗️",
  UnknEmo: "❓",
  DeadEmo: "🀄",
  AdminDownEmo: "🅰️",
  AdminUpEmo: "✳️",
  ShootDown: "🔘",


  //Cabel lenght pair Emoji
  OK_UP: "✅",
  OKEY: "☑️",
  CROSSTALK: "🔀",
  SHORT: "🆘",
  NOCABLE: "✴️",
  UNKNOWN: "🌀",
  ABNORMAL:"🆎",
  DOWN:"❎",
  // ✴️🆘🆎

  //Universal Emoji
  RedCircleEmo: "🔴",
  YellovCircleEmo: "🟡",
  GreenCircleEmo: "🟢",
  BlueCircleEmo: "🔵",
  BlackCircleEmo: "⚫️",
  PurpleCircleEmo: "🟣",

  BackEmo: "🔙",
  OkEmo: "🆗",
  CancelEmo: "🚫",
  ErrorEmo:"🛑",
  //Menu list emoji
  MagnifierEmo: "🔍",
  GearEmo: "⚙️",
  PcEmo: "💻",
  DoorEmo: "🚪",
  TechnologyEmo: "🧰",
  HiEmo: "👋",
  MagicEmo: "🔥",
  TestTubeEmo: "🧪",
  LockerEmo: "🔒",
  VlanEmo: "🔀",
  DDMEmo: "💥",
  SystemLogEmoji: "📃",
  MagicBallEmo: "🔮",
  MassIncidentEmo: "🏴‍☠️",
  P2PEmo: "🧬",
  LinkEmo: "🔗",
  NetworkEmo: "🌐",
  ShieldEmo: "🛡️",
  MoyaiEmo: "🗿",
  //Other Emoji
  ADMIN: "🏵",
  LOG: "📃",
  CLI: "📟",
  UserEmo: "👤",
  SantaEmo: "🎅",
  Group1: "📈",
  Group2: "📉",
  AlienEmo: "👽",
  SandTimeEmo: "⏳",
  RuporEmo: "📢",
  ShareEmo: "📤",
  LinerEMO: "📏",
  LockManagerEmo: "🔐",
  KeyEmo:"🔑"
};
